### ISSUE TITLE
The capture does not work for PlayCanvas examples

### ISSUE THREAD

**Issue by mvaligursky** [adobe/HumaneHamsterTrap#1]
Thanks for the tool, that looks like it could be super useful.

I tried to capture https://playcanvas.github.io/#/misc/hello-world and it does not seem to work - when I Enable and Reload, I does not offer me a file to save.

**Comment by starmole** [comment]
Thank you for the issue report. I will check what is happening with the playcanvas examples!

**Comment by starmole** [comment]
Can reproduce, probably has to do with how frames are setup on playcanvas. I don't see any code getting injected by the extension right now.

**Comment by mvaligursky** [comment]
Perhaps related to how requestAnimationFrame is handled?
https://github.com/playcanvas/engine/blob/039da2e23ca4a6dcc71630e5f3e79afe21553001/src/framework/app-base.js#L2141

**Comment by starmole** [comment]
fixed: https://github.com/adobe/HumaneHamsterTrap/commit/ffb3513a7c94bfa94476b18d582488f6e66e69cb
there is probably a better way to handle js urls, but this fixes the playcanvas case. 
there are still some errors where we are trying to inject worker blobs, but at least the hello world cube is captured now!
