### ISSUE TITLE
realsource.transferToImageBitmap is not a function

### ISSUE THREAD

**Issue by tlecoz** [adobe/HumaneHamsterTrap#2]
I installed the extension and tryed it with my project (it doesn't work in a worker) but I get an error after I clicked on "enable & reload"

![image](https://github.com/adobe/HumaneHamsterTrap/assets/272817/ac5ab842-5281-4703-8a91-2b98a64b5c86)

EDIT : just to precise, I'm working on a library that mimic webgpu with higher-level code and I'm currently trying to handle the "device lost" scenario.  I launch a demo, click on a button to destroy the device and try to rebuild everything.  I have no error message (anymore :) ) but my demo is still entirely black , that's what I want to debug (it's not a classic usecase , that's what I mean)

**Comment by starmole** [comment]
Thank you for the report. I will investigate. I did not do much testing with copyExternalImageToTexture. 
What type was the source object of your external image?

**Comment by tlecoz** [comment]
It's a canvas

**Comment by starmole** [comment]
Fixed for HTMLCanvasElement with a 2d canvas. Better messages for other (not yet supported) external images, like video or non 2d canvases. 

[fix issue 2, upload HTMLCanvasElement](https://github.com/adobe/HumaneHamsterTrap/commit/eed4f76d199a4578b003a15cdca34e787938babd)

Side note: There will probably be more (other errors) around device loss. I didn't test anything around that. 
(Also happily accepting PRs :))

**Comment by tlecoz** [comment]
Thank you for your work and your reactivity !

I will tell you if I find another error related to device loss
